### ISSUE TITLE
Feature Request: Fill Camel pack from water source

### ISSUE THREAD

**Issue by PigheadedGnu** [Funwayguy/EnviroMine#105]
It would be nice if you could fill the camel pack without crafting, perhaps by right clicking on a water source (or even filling it up 25% per click if the 'instafill' is an issue.)

I'd be happy to take a crack at implementing this if the feature is amenable.

Thanks for a great mod!

**Comment by thislooksfun** [comment]
The reason this hasn't been done yet is that we don't actually set the types of water in the world. We only check what type it gives when you actually grab a bottle of water from it. Also, the camel pack can only take clean ('normal') water. Basically, in order to make this work, we would need to redo the camel pack, and replace all the water blocks with custom ones. And that's not really something we feel like doing. Maybe in the future though.

**Comment by GenDeathrow** [comment]
Well don't be too quick to judge on this suggestion just yet.  I have a few ideas on this. This is actually something I have wanted to do for some time.  But at the moment I am rewriting some of the code for improvement. And will try to take a look at this possibility. TLF is right though as this feature isn't possible with the currant code.

**Comment by WolfieWaffle** [comment]
Well, I believe it is based off biomes, correct?
And the water bottles work differently depending on the biome...
So couldn't you just check what biome the right-clicked water source is in, like it appears to do with the water bottles, and only fill up the pack if it is in the correct biome? Maybe give a message like "That water is too salty" if you attempt to fill the pack in the wrong biome?

I don't really know exactly how this works, this is just a guess.

**Comment by GenDeathrow** [comment]
It is based off biomes... and that is a suggestion that may work. The water system has needed an update for a long time. Will see a lot going  .  On now for all of us.
