### ISSUE TITLE
Enviormine & Custom Npcs Rotting Food Bug

### ISSUE THREAD

**Issue by givemhell** [Funwayguy/EnviroMine#138]
i made an NPC that would sell food, but after some time the food rots in their storage, they then just sell rotten food

i disabled the rotting food feature for now, however its a bug that should be looked into, 
i talked to noppes this was the last bit from our convo

[11:41:39 PM] Givem hell: allright, good luck with the bug, hope to see it resolved in the future!
[11:42:01 PM] Noppes: probably cant
[11:42:14 PM] Noppes: it's a 100% that guys problem xD

**Comment by jermangarc** [comment]
You're right CustomNPC's has nothing to do with it. The traders are just like chests, they just store items to sell. Food rot works by adding nbt data to items, this is why you have problems stacking food with different rot percentages. If you want to sell food, you probably are going to have to turn off food rot altogether or increase your rot time; so food will last longer in the NPC's inventory. You can't just turn off food rot when it's being sold (kinda defeats the whole rotting feature anyhow). On my server we have food rot turned on, but increased the limit to 28 days, and we have a food market. Players selling food have to regularly restock the food because it'll go bad eventually, just like in real groceries, lol. We actually like it, because it creates demand for "farmers" in-game. Without rot, nobody wanted to buy food because everybody would just make mob grinders and have endless food... not anymore.

**Comment by BlazeGaming007** [comment]
I don't understand why this happens because it never happens to me when using custom npcs.

**Comment by GenDeathrow** [comment]
Technically its not a bug, because rotting is working as intended.. it would be a lot more work to add support for checking for their inventory. now maybe we will add in support to ignore certain inventorys, but that would be a long while... @jermangarc I like how your server has farmers.. thats something thats really cool that I had never thought of happening.
