### ISSUE TITLE
Feature Request: Configurable Torch burn-out time

### ISSUE THREAD

**Issue by PitchBright** [Funwayguy/EnviroMine#139]
These really should be configurable. They appear to burn out randomly right now. Some torches might last forever and some burn out within minutes. Ideally, if they are configurable, the user (or server) can configure them to suit their preference, so that Miners can use torches in a way that is effective, and yet realistic.

**Comment by Funwayguy** [comment]
The reason it isn't timed is because it would require torches to have tile entities. With the high amount of use torches recieve, the combined tick updates would start to cause noticable TPS lag especially on multiplayer servers. I will add configurable burn times if I can think of a better way of doing it I however as of right now there are no plans to change it.

**Comment by PitchBright** [comment]
Okay, great thanks!

**Comment by WolfieWaffle** [comment]
Wait, you don't use TileEntities? I'm making a torch burning out mod that uses them because I thought they were the only option... but my torches require having a fuel value, and they need to be able to burn out even in the inventory. Do you think it would be possible to do this without TE's, or are you just using a random chance to burn out every tick, meaning that a TE would be required for an actual fuel level.

Also, I was thinking about how it might cause lag, do you think my torch mod that uses TE's is going to be noticeably or significantly laggy?

Sorry I'm kind of hijacking this issue, but it looks closed anyways :P. If there is a better place to ask about this, please tell me and I'll move there.

**Comment by GenDeathrow** [comment]
@WolfieWaffle yeah, as many torches their are.. using TE would cause a lot of lag, because they are called every tick.. I believe he is using a random chance on them... I didn't write it.. you will have to search in the github code to get an idea what he did..
