### ISSUE TITLE
lava requires block update

### ISSUE THREAD

**Issue by shawn2408** [Funwayguy/EnviroMine#140]
i seem to have found an issue where my body temp is not affected by lava unless a block update happens

**Comment by GenDeathrow** [comment]
Hmmm.. very  .  Interesting. Mods? And what version you using.

**Comment by GenDeathrow** [comment]
I found the error out.. here. The issue was how we named our default custom config names... the custom configs get overriden.. go into your custom configs "minecraft.cfg"... look for lava... you will have flowing lava but normal lava will be missing.. 

Make sure you add both of these..

 flowing_lava {
        S:01.Name=minecraft:flowing_lava
        I:02.MetaID=-1
        S:03.DropName=
        I:04.DropMetaID=-1
        I:05.DropNumber=-1
        B:"06.Enable Temperature"=true
        D:07.Temperature=200.0
        D:"08.Air Quality"=-1.0
        D:09.Sanity=0.0
        S:10.Stability=none
        B:11.Slides=false
        B:"12.Slides When Wet"=false
    }

    lava {
        S:01.Name=minecraft:lava
        I:02.MetaID=-1
        S:03.DropName=
        I:04.DropMetaID=-1
        I:05.DropNumber=-1
        B:"06.Enable Temperature"=true
        D:07.Temperature=200.0
        D:"08.Air Quality"=-1.0
        D:09.Sanity=0.0
        S:10.Stability=none
        B:11.Slides=false
        B:"12.Slides When Wet"=false
    }
