### ISSUE TITLE
Stacking GUI

### ISSUE THREAD

**Issue by drago87** [Funwayguy/EnviroMine#98]
With v1.3.80 All the GUI (Temperature, Hydration, Air Quality and Sanity) is stacked ontop off eachouther in the top left corner and the setting in the config for moving them seams to be gone.

**Comment by thislooksfun** [comment]
You mean the option in the escape menu?

**Comment by Funwayguy** [comment]
I believe this is another bug related to @GenDeathrow's config issues

**Comment by GenDeathrow** [comment]
Guys it's been too hard for me to get to editing the fixes right now.  We have been sleep training my 8 month old.. It hasn't gone well.  Also are you taking about the config file or the ui settings file. Because they moved out of the old config file and you now edit the settings in the option menu in game.

**Comment by Funwayguy** [comment]
Should be fixed in 1.3.81
